const API = {}
API.GET_SUP_LIST = '/prd/getSupList'
API.GET_BRAND_LIST = '/prd/brand/getBrandList'
API.GET_MDID_LIST = '/prd/md/getMdIdList'
API.GET_CMM_CODE_LIST = '/cmm/getCmmCodeList'
API.GET_PRD_CLS_M_LIST = '/prdClsM/getPrdClsMList'
API.GET_SUB_SUP_LIST = '/prd/sups/getSubSupList'
API.GET_PRD_CLS_UDA_CD_ALL_LIST = '/prdClsM/getPrdClsUdaCDAllList'
API.GET_DIFF_PRD_CTGR_SHOP = '/prd/getDiffPrdCtgrShop'
API.GET_ETC_LRG_SHOP_LIST = '/prd/ecShop/getEtcLrgShopList'
API.GET_ETC_SUB_SHOP_LIST = '/prd/ecShop/getEtcSubShopList'
API.GET_PRD_REPORT_MST_INFO = '/prd/getPrdReportMstInfo'
API.GET_EC_SHOP_LIST = '/prd/ecShop/getEcShopList'
API.GET_PRD_CNTNT_LIST = '/prd/cntnt/getPrdCntntList'
API.GET_PRD_CLS_BY_BASE_VAL_LIST = '/prdClsM/getPrdClsByBaseValList'
API.GET_PRD_BASE = '/prd/getPrdBase'
API.SET_PRD_BASE = '/prd/setPrdBase'
API.GET_PRD_LIST_TO = '/prd/getPrdListto'
API.GET_MD_EMP_LIST = '/prd/md/getMdEmpList'
API.GET_PRD_LIST = '/prd/popup/getPrdList'
API.SAVE_CNTNT_LIST = '/api/prd/cntnt/saveCntntList'
API.MODIFY_PUB_IMG_CHG = '/prd/cntnt/modifyPubImgChg'
API.REMOVE_CNTNT_LIST = '/prd/cntnt/removeCntntList'
API.ATTACHMENT = '/cmm/attachment'
API.ADD_PRD_BANNER_IMG_LIST = '/prd/cntnt/addPrdBnnrImgList'
API.REMOVE_BANNER_IMG_LIST = '/prd/cntnt/removePrdBnnrImgList'

export default API
